CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS excuses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  situation TEXT NOT NULL,
  category TEXT NOT NULL,
  excuse_text TEXT NOT NULL,
  believability_score INTEGER NOT NULL,
  creativity_score INTEGER NOT NULL,
  share_id TEXT UNIQUE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
